Update 2-release.yml

diff --git a/.github/workflows/2-release.yml b/.github/workflows/2-release.yml
--- a/.github/workflows/2-release.yml
+++ b/.github/workflows/2-release.yml
@@ -12,24 +12,26 @@ on:
 jobs:
   checks:
     runs-on: ubuntu-latest
+    if: |
+        (github.event_name != 'workflow_run') ||
+        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')    
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v2
-      - name: Check workflow
+      - name: Check workflow (${{ github.event_name }} ${{ github.event.workflow_run.conclusion }})
         run: | 
           echo "🧪 Checking triggering workflow..."
           echo "[Release] ref: ${{ github.ref }} - event: ${{ github.event_name }} - conclusion: ${{ github.event.workflow_run.conclusion }}"
           echo "[Release] condition: ${{ (github.event_name != 'workflow_run') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}"
 
-      - name: Fail the build if something went wrong
-        if: |
-          contains(job.status, 'failure') || 
-          contains(steps.*.outcome, 'failure') ||
-          (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success')
-        run: exit 1
+  #     - name: Fail the build if something went wrong
+  #       if: |
+  #         contains(job.status, 'failure') || 
+  #         contains(steps.*.outcome, 'failure') ||
+  #         (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion != 'success')
+  #       run: exit 1
 
   release:
     runs-on: ubuntu-latest
+    needs: checks
     if: |
         (github.event_name != 'workflow_run') ||
         (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
